# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GrLassoCpp <- function(Z, lambdainvL) {
    .Call('_DDSA_GrLassoCpp', PACKAGE = 'DDSA', Z, lambdainvL)
}

ProxGrLassoCpp <- function(lambda1, lambda2, WtY, WtWList, BtBList, Omega) {
    .Call('_DDSA_ProxGrLassoCpp', PACKAGE = 'DDSA', lambda1, lambda2, WtY, WtWList, BtBList, Omega)
}

MatGrLassoCpp <- function(Z, etainL, p, q) {
    .Call('_DDSA_MatGrLassoCpp', PACKAGE = 'DDSA', Z, etainL, p, q)
}

CV_PCTrainingErrCpp <- function(U, TrainIndex, SNeList, AtA, AtY, p, q) {
    .Call('_DDSA_CV_PCTrainingErrCpp', PACKAGE = 'DDSA', U, TrainIndex, SNeList, AtA, AtY, p, q)
}

ADAMCpp <- function(TrainIndex, R, eta1, eta2, SNeList, AtAList, AtYList, Omega) {
    .Call('_DDSA_ADAMCpp', PACKAGE = 'DDSA', TrainIndex, R, eta1, eta2, SNeList, AtAList, AtYList, Omega)
}

